platform :ios, '9.0'
use_frameworks!

target 'engr' do
    pod 'Alamofire','~> 4.2.0'
    pod 'SnapKit','~> 3.0’
    pod 'Kingfisher','~> 3.1.0’
    pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'
    pod 'ObjectMapper', '~> 2.0.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'MJRefresh' 
    pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
   
    pod 'Bugly'
    pod 'BaiduMapKit' #百度地图SDK
#    pod 'GrowingIO','~> 0.9.41'
end
